// V003: Seed genre template data (mirrors Rust V003)
export const sql = `
INSERT OR IGNORE INTO genre_templates (id, genre_id, genre_name, world_framework, volume_rhythm, character_archetypes, thrill_params, taboo_rules, default_min_chapter_words, default_max_chapter_words, naming_style, naming_examples) VALUES
('gt-001', 'xuanhuan', '玄幻', '{"type":"fantasy","power_system":"修炼体系","levels":"凡人-筑基-金丹-元婴-化神-大乘-渡劫","world_origin":"远古传承"}', '{"total_volumes":8,"rhythm":"起承转合","volume_goals":["入门","成长","历练","突破","争霸","守护","渡劫","超脱"]}', '{"protagonist":"天赋异禀+坚韧意志","mentor":"神秘高人","rival":"同门/宿敌","ally":"义兄弟/灵宠"}', '{"hook_type":"境界突破","climax_type":"以弱胜强","tension_source":"资源争夺+宗门斗争"}', '{"rules":["不可违背修炼逻辑","不可跳跃境界","战力体系自洽"]}', 2500, 5000, '古风+意境', '["叶辰","苏沐橙","萧炎","林动"]'),
('gt-002', 'wuxia', '武侠', '{"type":"jianghu","power_system":"武功招式+内力","levels":"三流-二流-一流-绝顶-宗师-天人","world_origin":"江湖传承"}', '{"total_volumes":6,"rhythm":"侠义征途","volume_goals":["入江湖","扬名","恩怨","大义","归隐","传承"]}', '{"protagonist":"侠义心肠+奇遇","mentor":"退隐高手","rival":"正邪对立","ally":"知己/红颜"}', '{"hook_type":"恩怨揭秘","climax_type":"决战巅峰","tension_source":"正邪冲突+情义抉择"}', '{"rules":["武功有出处","内力有极限","江湖有规矩"]}', 2500, 5000, '侠义+诗意', '["令狐冲","乔峰","张无忌","杨过"]'),
('gt-003', 'xianxia', '仙侠', '{"type":"cultivation","power_system":"修仙问道","levels":"练气-筑基-结丹-元婴-化神-合体-大乘-渡劫","world_origin":"天道法则"}', '{"total_volumes":8,"rhythm":"修仙路","volume_goals":["入道","筑基","游历","悟道","渡劫","飞升","仙界","超脱"]}', '{"protagonist":"悟性超群+道心坚定","mentor":"仙人指路","rival":"道争对手","ally":"道侣/灵兽"}', '{"hook_type":"道劫降临","climax_type":"逆天改命","tension_source":"天劫+道争+情劫"}', '{"rules":["天道不可违（除非渡劫）","因果必还","道心为本"]}', 2500, 5500, '清雅+道韵', '["韩立","白浅","张小凡","花小骨"]'),
('gt-004', 'dushi', '都市', '{"type":"modern_city","power_system":"财富+人脉+能力","levels":"普通人-小成-中产-精英-巨头-传奇","world_origin":"现实社会"}', '{"total_volumes":5,"rhythm":"逆袭路","volume_goals":["起步","积累","危机","崛起","巅峰"]}', '{"protagonist":"能力突出+机遇","mentor":"行业前辈","rival":"商业对手","ally":"伙伴/爱人"}', '{"hook_type":"危机逆转","climax_type":"商业决战","tension_source":"竞争+阴谋+情感"}', '{"rules":["逻辑自洽","不可过度金手指","社会规则约束"]}', 2000, 4500, '现代+干练', '["叶辰","秦升","陆涛","苏锐"]'),
('gt-005', 'lishi', '历史', '{"type":"historical","power_system":"权谋+军事+人脉","levels":"白身-小吏-地方-朝堂-权臣-帝王","world_origin":"历史进程"}', '{"total_volumes":6,"rhythm":"权谋路","volume_goals":["入局","站稳","布局","博弈","定鼎","开太平"]}', '{"protagonist":"深谋远虑+手腕","mentor":"老臣/谋士","rival":"政敌","ally":"忠臣/红颜"}', '{"hook_type":"朝局突变","climax_type":"关键战役/政变","tension_source":"权力斗争+家国抉择"}', '{"rules":["尊重历史大势","人物行为合乎时代","不可过度穿越者优势"]}', 2500, 5500, '典雅+厚重', '["嬴政","李世民","王安石","岳飞"]'),
('gt-006', 'kehuan', '科幻', '{"type":"sci-fi","power_system":"科技+进化","levels":"文明等级或科技阶段","world_origin":"科学体系"}', '{"total_volumes":5,"rhythm":"探索路","volume_goals":["发现","研究","突破","危机","超越"]}', '{"protagonist":"理性+好奇心","mentor":"前辈科学家","rival":"理念对立者","ally":"团队伙伴"}', '{"hook_type":"未知发现","climax_type":"文明危机","tension_source":"未知+伦理+生存"}', '{"rules":["科学逻辑自洽","因果链清晰","技术树合理"]}', 2500, 5000, '理性+前瞻', '["罗辑","程心","叶文洁","章北海"]'),
('gt-007', 'lingyi', '灵异', '{"type":"supernatural","power_system":"灵力+术法","levels":"感知-驱邪-镇灵-通灵-渡灵","world_origin":"阴阳两界"}', '{"total_volumes":5,"rhythm":"驱灵路","volume_goals":["初灵","觉醒","历练","真相","超脱"]}', '{"protagonist":"灵觉敏锐+胆大心细","mentor":"老前辈","rival":"邪灵/对手","ally":"灵伴/搭档"}', '{"hook_type":"灵异事件","climax_type":"灵异对决","tension_source":"未知恐惧+人性考验"}', '{"rules":["灵异有规则","因果有循环","人心最诡"]}', 2000, 4000, '诡异+氛围', '["沈夜","林动","张玄","陈默"]'),
('gt-008', 'junshi', '军事', '{"type":"military","power_system":"军事+谋略","levels":"士兵-尉官-校官-将官-统帅","world_origin":"战争体系"}', '{"total_volumes":5,"rhythm":"征战路","volume_goals":["入伍","历练","领兵","大战","功成"]}', '{"protagonist":"勇猛+谋略","mentor":"老将","rival":"敌方将领","ally":"战友"}', '{"hook_type":"战局逆转","climax_type":"关键战役","tension_source":"生死+家国+信念"}', '{"rules":["军事逻辑合理","不可过度个人英雄","战争有代价"]}', 2500, 5000, '刚毅+大气', '["楚云","韩猛","赵风","卫青"]'),
('gt-009', 'yanqing', '言情', '{"type":"romance","power_system":"情感+成长","levels":"相遇-心动-暧昧-确定-考验-相守","world_origin":"情感世界"}', '{"total_volumes":4,"rhythm":"情感路","volume_goals":["相遇","心动","考验","相守"]}', '{"protagonist":"独立+善良","love_interest":"深情+有故事","rival":"情敌","ally":"闺蜜/兄弟"}', '{"hook_type":"情感转折","climax_type":"情感爆发","tension_source":"误会+阻碍+选择"}', '{"rules":["情感递进自然","角色行为合理","不可强行虐恋"]}', 2000, 4000, '细腻+浪漫', '["顾漫","何以琛","肖奈","夜华"]'),
('gt-010', 'youxi', '游戏', '{"type":"game_world","power_system":"游戏机制","levels":"新手-精英-史诗-传说-神话","world_origin":"游戏系统"}', '{"total_volumes":5,"rhythm":"升级路","volume_goals":["入游戏","崛起","争霸","真相","超越"]}', '{"protagonist":"天赋+运气+努力","mentor":"隐藏高手","rival":"公会对手","ally":"队友/宠物"}', '{"hook_type":"隐藏任务/副本","climax_type":"BOSS战/公会战","tension_source":"竞争+机制+剧情"}', '{"rules":["游戏机制自洽","不可过度BUG利用","玩家行为合理"]}', 2500, 5000, '轻松+热血', '["叶修","林凡","张飞","苏沐橙"]');

INSERT INTO _migrations (version, name, applied_at) VALUES (3, 'seed_genre_templates', datetime('now'));
`;
