// V004: Seed soul template data (mirrors Rust V004)
export const sql = `
INSERT OR IGNORE INTO soul_templates (id, soul_name, category, genre_compat, personality_json, speech_json, behavior_json, relationships_json, is_builtin, created_at, updated_at) VALUES
('st-001', '冷面强者', 'protagonist', '["xuanhuan","xianxia","wuxia"]', '{"core":"外表冷漠内心热忱","traits":["坚忍","寡言","重义","孤独"],"values":["实力为尊","守护至亲"],"fears":["失去珍视之人","无力保护"]}', '{"tone":"简洁有力","vocabulary":"精炼","habits":["少说废话","点破关键","沉默即拒绝"],"catchphrases":["不必多说","看招"]}', '{"decision":"理性优先","under_pressure":"越战越勇","social":"被动社交","conflict":"直接解决"}', '{"family":"深沉守护","friend":"少而精","lover":"笨拙深情","enemy":"绝不留情"}', 1, '2024-01-01T00:00:00Z', '2024-01-01T00:00:00Z'),
('st-002', '热血少年', 'protagonist', '["xuanhuan","wuxia","youxi","junshi"]', '{"core":"热血正义永不言弃","traits":["乐观","冲动","重情","直率"],"values":["友情","梦想","正义"],"fears":["同伴受伤","梦想破灭"]}', '{"tone":"热情高昂","vocabulary":"口语化","habits":["大声说话","口头禅多","情绪外露"],"catchphrases":["我绝不会放弃","一定要变得更强"]}', '{"decision":"直觉优先","under_pressure":"爆发潜力","social":"主动社交","conflict":"正面迎击"}', '{"family":"孝顺感恩","friend":"义气深重","lover":"迟钝但真诚","enemy":"堂堂正正"}', 1, '2024-01-01T00:00:00Z', '2024-01-01T00:00:00Z'),
('st-003', '智者谋士', 'protagonist', '[''lishi'',''junshi'',''dushi'',''xuanhuan'']', '{"core":"深谋远虑运筹帷幄","traits":["冷静","多疑","洞察","隐忍"],"values":["大局","结果","智慧"],"fears":["算计失误","被人看穿"]}', '{"tone":"从容不迫","vocabulary":"文雅含蓄","habits":["话中有话","引经据典","点到为止"],"catchphrases":["且看后事如何","一切尽在掌握"]}', '{"decision":"深思熟虑","under_pressure":"冷静分析","social":"目的社交","conflict":"智取为上"}', '{"family":"疏远但牵挂","friend":"极少数知己","lover":"克制但深沉","enemy":"利用与消灭"}', 1, '2024-01-01T00:00:00Z', '2024-01-01T00:00:00Z'),
('st-004', '逍遥浪子', 'protagonist', '["wuxia","xianxia","xuanhuan"]', '{"core":"自由不羁笑看人生","traits":["洒脱","风流","重情","叛逆"],"values":["自由","真情","酒"],"fears":["被束缚","虚伪"]}', '{"tone":"洒脱幽默","vocabulary":"俚俗有趣","habits":["调侃","自嘲","醉酒高歌"],"catchphrases":["人生得意须尽欢","管他呢"]}', '{"decision":"随心所欲","under_pressure":"置之死地而后生","social":"广交天下","conflict":"以巧制胜"}', '{"family":"避而不谈","friend":"四海皆兄弟","lover":"处处留情","enemy":"玩世不恭地击败"}', 1, '2024-01-01T00:00:00Z', '2024-01-01T00:00:00Z'),
('st-005', '霸道总裁', 'love_interest', '["dushi","yanqing"]', '{"core":"掌控一切只为你低头","traits":["强势","专一","傲娇","护短"],"values":["效率","控制","爱情"],"fears":["失去控制","被拒绝"]}', '{"tone":"命令式","vocabulary":"简短有力","habits":["不解释","替人做决定","偶尔温柔"],"catchphrases":["我说了算","你只能是我的"]}', '{"decision":"独断专行","under_pressure":"更强硬","social":"上位者社交","conflict":"碾压解决"}', '{"family":"责任驱动","friend":"极少","lover":"霸道专一","enemy":"直接碾压"}', 1, '2024-01-01T00:00:00Z', '2024-01-01T00:00:00Z'),
('st-006', '温婉佳人', 'love_interest', '["yanqing","lishi","wuxia"]', '{"core":"温柔坚韧如水","traits":["温柔","坚韧","聪慧","隐忍"],"values":["家庭","真情","善良"],"fears":["被抛弃","无力挽回"]}', '{"tone":"柔和细腻","vocabulary":"文雅含蓄","habits":["轻声细语","体贴入微","关键时刻果断"],"catchphrases":["我没事","你一定要平安"]}', '{"decision":"兼顾他人","under_pressure":"坚韧支撑","social":"温和社交","conflict":"以柔克刚"}', '{"family":"全心付出","friend":"温柔可靠","lover":"深情守候","enemy":"不惹事不惧事"}', 1, '2024-01-01T00:00:00Z', '2024-01-01T00:00:00Z'),
('st-007', '疯批反派', 'antagonist', '["xuanhuan","xianxia","dushi","junshi"]', '{"core":"为达目的不择手段","traits":["偏执","聪明","残忍","执念"],"values":["目标","权力","复仇"],"fears":["目标失败","被超越"]}', '{"tone":"阴冷或癫狂","vocabulary":"尖锐刻薄","habits":["嘲讽","自言自语","极端言行"],"catchphrases":["哈哈哈...你以为你赢了","这世间不过如此"]}', '{"decision":"极端手段","under_pressure":"更加疯狂","social":"利用一切","conflict":"不择手段"}', '{"family":"冷漠或执念","friend":"不存在","lover":"扭曲占有","enemy":"残酷无情"}', 1, '2024-01-01T00:00:00Z', '2024-01-01T00:00:00Z'),
('st-008', '忠义之士', 'supporting', '["wuxia","junshi","lishi"]', '{"core":"忠义为先死而后已","traits":["忠诚","正直","刚烈","朴实"],"values":["忠义","信诺","家国"],"fears":["背信弃义","忠义两难"]}', '{"tone":"铿锵有力","vocabulary":"朴实直白","habits":["言出必行","不卑不亢","直来直去"],"catchphrases":["某愿效死力","大丈夫当如是"]}', '{"decision":"义字当头","under_pressure":"宁折不弯","social":"以诚待人","conflict":"正面硬刚"}', '{"family":"舍家为国","friend":"生死之交","lover":"含蓄深沉","enemy":"堂堂正正对阵"}', 1, '2024-01-01T00:00:00Z', '2024-01-01T00:00:00Z'),
('st-009', '妖魅邪修', 'antagonist', '["xianxia","xuanhuan","lingyi"]', '{"core":"以魅惑人心为手段","traits":["魅惑","狡诈","善变","残忍"],"values":["力量","享乐","自由"],"fears":["被反制","失去魅力"]}', '{"tone":"妖魅诱惑","vocabulary":"暧昧含混","habits":["话中有话","声东击西","欲擒故纵"],"catchphrases":["来嘛~别怕","你逃不掉的"]}', '{"decision":"利己为主","under_pressure":"以退为进","social":"魅惑利用","conflict":"暗算诡计"}', '{"family":"无概念","friend":"利用关系","lover":"游戏人间","enemy":"阴毒手段"}', 1, '2024-01-01T00:00:00Z', '2024-01-01T00:00:00Z'),
('st-010', '科技天才', 'protagonist', '["kehuan","youxi","dushi"]', '{"core":"用科技改变世界","traits":["理性","执着","孤僻","理想主义"],"values":["真理","进步","创造"],"fears":["技术被滥用","创造失败"]}', '{"tone":"理性精确","vocabulary":"专业术语+简洁","habits":["数据化表达","自言自语思考","忽略社交礼仪"],"catchphrases":["数据显示...","让我计算一下"]}', '{"decision":"数据驱动","under_pressure":"超常专注","social":"社恐但专业领域自信","conflict":"技术碾压"}', '{"family":"疏远","friend":"极少数同行","lover":"笨拙但真诚","enemy":"技术对决"}', 1, '2024-01-01T00:00:00Z', '2024-01-01T00:00:00Z');

INSERT INTO _migrations (version, name, applied_at) VALUES (4, 'seed_soul_templates', datetime('now'));
`;
